
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    networks:
      - claims-network
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: claimsdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: claimspass123

  claims-api:
    build:
      context: ./apps/claims-api
      dockerfile: Dockerfile
    container_name: claims-api
    restart: always
    ports:
      - '3000:3000'
    networks:
      - claims-network
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/claims_db
      NODE_ENV: development
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: claimspass123
    volumes:
      - ./apps/claims-api:/app
      - /app/node_modules
    command: npm run start

  claims-front:
    build:
      context: ./apps/claims-front
      dockerfile: Dockerfile
    container_name: claims-front
    restart: always
    ports:
      - '4200:80'
    networks:
      - claims-network
    depends_on:
      - claims-api

networks:
  claims-network:
    driver: bridge

volumes:
  mongo_data: